# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Alaa Attya's Tech blog
email: alaa.attya91@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Software engineer who cares about engineering principles #PHP #Gopher #JS #ROR #java 
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: AlaaAttya
github_username:  AlaaAttya

# Build settings
#theme: minima
theme: jekyll-text-theme
text_skin: default
highlight_theme: default

## => Plugins
##############################
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji

## => Paginate
##############################
paginate: 8
paginate_path: /page:num # don't change this unless for special need  

## => Sources
##############################
sources: # bootcdn (default), unpkg

## => Sharing
##############################
sharing:
  provider: "addthis"

  ## AddThis
  addthis:
    id: "ra-6141044a78e39f52"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: article
      sharing: true
      license: true
      comment: true
      aside:
        toc: true
      show_edit_on_github: true
      show_subscribe: true
      pageview: true

## => Comments
##############################
comments:
  provider: "disqus"

  ## Disqus
  disqus:
    shortname: "http-alaa-ninja"   

jekyll:
  environment: production


## => Analytics
##############################
analytics:
  provider: "google"

  ## Google Analytics
  google:
    tracking_id : "G-FPK1KRB22T"
    anonymize_ip: false # Anonymize IP tracking for Analytics  

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
