version: '2'

services:
  jekyll:
    image: jekyll/jekyll:4.2.2
    command: jekyll serve --watch --force_polling --verbose --trace
    ports:
      - "4000:4000"
    environment:
      JEKYLL_ENV: "production"
    volumes:
      - .:/srv/jekyll
      - type: tmpfs
        target: /srv/jekyll/.jekyll-cache
