---

- name: initiatlzing my jekyll blog
  connection: ansible.netcommon.network_cli
  hosts: nodes
  gather_facts: false
  tasks:

  - name: Update apt packages
    become: true
    apt:
      upgrade: no
      update_cache: yes
      cache_valid_time: 86400 #One day

  - name: installing pre-reqs
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - build-essential
      - gcc
      - git
      - make
      - ruby-full
      - ruby-dev
      - zlib1g-dev
      - ruby-bundler
    
  - name: installing Ruby Gems
    gem:
      name: "{{ item.name }}"
      state: present
      user_install: no
      version: "{{ item.version }}"
    with_items:
      - { name: bundler, version: latest }
      - { name: jekyll, version: 4.2.0 }
  
  - name: add github to known hosts
    ansible.builtin.shell:
      cmd: ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
  
  - name: clone my blog repository
    ansible.builtin.git: 
      repo: git@github.com:AlaaAttya/my-blog.git 
      dest: /home/deployer/my-blog
      key_file: ~/.ssh/id_rsa
      force: true
  
  - name: ignore git file mode modifications
    ansible.builtin.shell:
      cmd: cd /home/deployer/my-blog && git config core.fileMode false
  
  - name: install dependencies
    ansible.builtin.shell:
      cmd: cd /home/deployer/my-blog && bundle install 

  - name: build static site
    ansible.builtin.shell:
      chdir: /home/deployer/my-blog
      cmd: bundle exec jekyll build

  - name: install nginx
    apt: 
      name: nginx 
      state: latest      

  - name: copy nginx cofigs
    template:
      src: templates/nginx.cfg
      dest: /etc/nginx/sites-available/default
      owner: root
      group: root
      mode: 0644  

  - name: copy ads.txt
    ansible.builtin.copy:
      src: files/ads.txt
      dest: /home/deployer/my-blog/_site/ads.txt  

  - name: restart nginx
    become: true
    ansible.builtin.shell:
      cmd: systemctl status nginx
    ignore_errors: yes          
